# Generated by Project Igniter

$ErrorActionPreference = "Stop"

$STATE_BASE = "$env:HOME/.local/share/project-igniter"
$SCRIPT_DIR = Split-Path $PSScriptRoot -Parent
$PROJECT_KEY = Split-Path (Split-Path $SCRIPT_DIR -Parent) -Leaf
$ENV_NAME = Split-Path $SCRIPT_DIR -Leaf
$SAFE_PROJECT = [regex]::Replace($PROJECT_KEY, "[^a-zA-Z0-9]", "_")
$SAFE_ENV = [regex]::Replace($ENV_NAME, "[^a-zA-Z0-9]", "_")
$PROJECT_STATE = Join-Path $STATE_BASE "$SAFE_PROJECT/$SAFE_ENV"

New-Item -ItemType Directory -Path $PROJECT_STATE -Force | Out-Null

function Load-State($v) {
  $f = Join-Path $PROJECT_STATE $v
  if (Test-Path $f) { Set-Variable -Name $v -Value (Get-Content $f) -Scope 1 }
}

function Save-State($v, $val) {
  $val | Out-File -FilePath (Join-Path $PROJECT_STATE $v) -Encoding UTF8
}

$NEXT = 'd13cbb57-b04e-4e79-b437-44a1374da019'

while ($NEXT) {
  switch ($NEXT) {
    'd13cbb57-b04e-4e79-b437-44a1374da019') {
      bun run tauri dev
      if ($LASTEXITCODE -eq 0) {
        $NEXT = ''
      } else {
        $NEXT = ''
      }
    }
  }
}
