#! /usr/bin/env bash
# Generated by Project Igniter

set -o pipefail

STATE_BASE="${HOME}/.local/share/project-igniter"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_KEY="$(basename "$(dirname "$SCRIPT_DIR")")"
ENV_NAME="$(basename "$SCRIPT_DIR")"
SAFE_PROJECT="$(echo "$PROJECT_KEY" | sed "s/[^a-zA-Z0-9]/_/g")"
SAFE_ENV="$(echo "$ENV_NAME" | sed "s/[^a-zA-Z0-9]/_/g")"
PROJECT_STATE="${STATE_BASE}/${SAFE_PROJECT}/${SAFE_ENV}"

mkdir -p "${PROJECT_STATE}" 2>/dev/null

load_state() { local v="$1"; local f="${PROJECT_STATE}/${v}"; [ -f "$f" ] && eval "${v}="$(cat "$f")""; }
save_state() { local v="$1"; shift; echo "$*" > "${PROJECT_STATE}/${v}"; }

NEXT="d13cbb57-b04e-4e79-b437-44a1374da019"

while [ -n "$NEXT" ]; do
  case "$NEXT" in
    d13cbb57-b04e-4e79-b437-44a1374da019)
      bun run tauri dev
      if [ $? -eq 0 ]; then
        NEXT=""
      else
        NEXT=""
      fi
      ;;
  esac
done
