#! /usr/bin/env bash
# Generated by Project Igniter

set -o pipefail

# ── Locate .project-igniter root ──
PROJECT_IGNITER_DIR=""
CURRENT_DIR="$PWD"
while [ "$CURRENT_DIR" != "/" ]; do
  if [ -d "$CURRENT_DIR/.project-igniter" ]; then
    PROJECT_IGNITER_DIR="$CURRENT_DIR/.project-igniter"
    break
  fi
  CURRENT_DIR="$(dirname "$CURRENT_DIR")"
done
if [ -z "$PROJECT_IGNITER_DIR" ]; then
  echo "Error: .project-igniter not found in any parent directory" >&2
  exit 1
fi
WORKFLOWS_JSON="$PROJECT_IGNITER_DIR/workflows.json"
PROJECT_ROOT="$(cd "$PROJECT_IGNITER_DIR/.." && pwd)"

# ── Parse flags ──
PROJECT_KEY=""
ENV=""
RESET=false
STATUS=false

while [ $# -gt 0 ]; do
  case "$1" in
    --proj) PROJECT_KEY="$2"; shift 2 ;;
    --env) ENV="$2"; shift 2 ;;
    --reset) RESET=true; shift ;;
    --status) STATUS=true; shift ;;
    --help)
      echo "Usage: setup.sh [--proj <name>] [--env <name>] [--reset] [--status]"
      echo ""
      echo "  --proj <name>  Target project (default: auto-detect from cwd)"
      echo "  --env <name>   Target environment (default: project default)"
      echo "  --reset        Clear all stored state for this project/env"
      echo "  --status       Show current configuration status"
      exit 0
      ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
done

# ── Determine project key from cwd (fallback) ──
DEFAULT_ENV="dev"
if [ -z "$PROJECT_KEY" ]; then
  CWD_REL="${PWD#$PROJECT_ROOT}"
  CWD_REL="${CWD_REL#/}"
  CWD_REL="${CWD_REL:-.}"

  case "$CWD_REL" in
  ".")
    PROJECT_KEY="root"
    DEFAULT_ENV="dev"
    ;;
    *)
      echo "Error: current directory does not match any project in workflows.json" >&2
      echo "Use --proj <name> to specify a project." >&2
      exit 1
      ;;
  esac
fi

# ── Default env ──
if [ -z "$ENV" ]; then
  ENV="$DEFAULT_ENV"
fi

# ── State management ──
STATE_BASE="${HOME}/.local/share/project-igniter"
SAFE_PROJECT="$(echo "$PROJECT_KEY" | sed "s/[^a-zA-Z0-9]/_/g")"
SAFE_ENV="$(echo "$ENV" | sed "s/[^a-zA-Z0-9]/_/g")"
STATE_DIR="${STATE_BASE}/${SAFE_PROJECT}/${SAFE_ENV}"
STATE_META="${STATE_DIR}/meta"
mkdir -p "$STATE_DIR" 2>/dev/null

# ── Commands ──
if [ "$RESET" = true ]; then
  rm -rf "$STATE_DIR"
  echo "State cleared for project=${PROJECT_KEY} env=${ENV}"
  exit 0
fi

if [ "$STATUS" = true ]; then
  echo "Project: ${PROJECT_KEY}"
  echo "Environment: ${ENV}"
  echo "Schema: ${CURRENT_SCHEMA}"
  if [ -f "$STATE_META" ]; then
    echo "Last run: $(grep "LAST_RUN=" "$STATE_META" | cut -d= -f2)"
  fi
  echo ""
  if [ -d "$STATE_DIR" ]; then
    for f in "$STATE_DIR"/*; do
      [ "$(basename "$f")" = "meta" ] && continue
      echo "  $(basename "$f") = $(cat "$f")"
    done
  fi
  exit 0
fi

# ── Read schema ──
CURRENT_SCHEMA="$(grep -o '"schema": *[0-9]*' "$WORKFLOWS_JSON" | grep -o '[0-9]*$' | head -1)"
STORED_SCHEMA="$(test -f "$STATE_META" && grep "SCHEMA=" "$STATE_META" | cut -d= -f2 || echo "")"

# ── Drift detection ──
if [ -n "$STORED_SCHEMA" ] && [ "$STORED_SCHEMA" != "$CURRENT_SCHEMA" ]; then
  echo "Setup scripts updated to version ${CURRENT_SCHEMA} (was ${STORED_SCHEMA})."
fi

# ── Update state meta ──
echo "SCHEMA=${CURRENT_SCHEMA}" > "$STATE_META"
echo "LAST_RUN=$(date +%Y-%m-%d)" >> "$STATE_META"

# ── Run target script ──
TARGET_SCRIPT="$PROJECT_IGNITER_DIR/scripts/${PROJECT_KEY}/${ENV}/setup.sh"
if [ ! -f "$TARGET_SCRIPT" ]; then
  echo "Error: no setup script found for project=${PROJECT_KEY} env=${ENV}" >&2
  echo "  Expected: $TARGET_SCRIPT" >&2
  exit 1
fi

exec bash "$TARGET_SCRIPT"
