# Generated by Project Igniter

$ErrorActionPreference = "Stop"

# ── Locate .project-igniter root ──
$PROJECT_IGNITER_DIR = $null
$CURRENT_DIR = Get-Location
while ($CURRENT_DIR -ne $null -and $CURRENT_DIR -ne [System.IO.Path]::GetPathRoot($CURRENT_DIR)) {
  $testPath = Join-Path $CURRENT_DIR ".project-igniter"
  if (Test-Path $testPath) {
    $PROJECT_IGNITER_DIR = $testPath
    break
  }
  $CURRENT_DIR = Split-Path $CURRENT_DIR -Parent
}
if ($null -eq $PROJECT_IGNITER_DIR) {
  Write-Error ".project-igniter not found in any parent directory"
  exit 1
}
$WORKFLOWS_JSON = Join-Path $PROJECT_IGNITER_DIR "workflows.json"
$PROJECT_ROOT = Split-Path $PROJECT_IGNITER_DIR -Parent

# ── Parse flags ──
$PROJECT_KEY = ""
$ENV = ""
$RESET = $false
$STATUS = $false

while ($args.Count -gt 0) {
  switch ($args[0]) {
    "--proj") { $PROJECT_KEY = $args[1]; $args = $args[2..$args.Count] }
    "--env") { $ENV = $args[1]; $args = $args[2..$args.Count] }
    "--reset") { $RESET = $true; $args = $args[1..$args.Count] }
    "--status") { $STATUS = $true; $args = $args[1..$args.Count] }
    "--help") {
      Write-Host "Usage: setup.ps1 [--proj <name>] [--env <name>] [--reset] [--status]"
      Write-Host ""
      Write-Host "  --proj <name>  Target project (default: auto-detect from cwd)"
      Write-Host "  --env <name>   Target environment (default: project default)"
      Write-Host "  --reset        Clear all stored state for this project/env"
      Write-Host "  --status       Show current configuration status"
      exit 0
    }
    default { Write-Error "Unknown flag: $($args[0])"; exit 1 }
  }
}

# ── Determine project key from cwd (fallback) ──
$DEFAULT_ENV = "dev"
if ([string]::IsNullOrEmpty($PROJECT_KEY)) {
  $CWD_REL = (Get-Location).FullName.Substring($PROJECT_ROOT.Length).TrimStart("/\")
  if ([string]::IsNullOrEmpty($CWD_REL)) { $CWD_REL = "." }

  switch -Wildcard ($CWD_REL) {
    ".") {
      $PROJECT_KEY = 'root'
      $DEFAULT_ENV = 'dev'
    }
    default {
      Write-Error "current directory does not match any project in workflows.json"
      Write-Error "Use --proj <name> to specify a project."
      exit 1
    }
  }
}

# ── Default env ──
if ([string]::IsNullOrEmpty($ENV)) {
  $ENV = $DEFAULT_ENV
}
$STATE_BASE = "$env:HOME/.local/share/project-igniter"
$SAFE_PROJECT = [regex]::Replace($PROJECT_KEY, "[^a-zA-Z0-9]", "_")
$SAFE_ENV = [regex]::Replace($ENV, "[^a-zA-Z0-9]", "_")
$STATE_DIR = Join-Path $STATE_BASE "$SAFE_PROJECT/$SAFE_ENV"
$STATE_META = Join-Path $STATE_DIR "meta"
New-Item -ItemType Directory -Path $STATE_DIR -Force | Out-Null

# ── Commands ──
if ($RESET) {
  Remove-Item -Path $STATE_DIR -Recurse -Force -ErrorAction SilentlyContinue
  Write-Host "State cleared for project=$PROJECT_KEY env=$ENV"
  exit 0
}

if ($STATUS) {
  Write-Host "Project: $PROJECT_KEY"
  Write-Host "Environment: $ENV"
  Write-Host "Schema: $CURRENT_SCHEMA"
  if (Test-Path $STATE_META) {
    $lastRun = (Get-Content $STATE_META | Select-String "LAST_RUN=(.*)").Matches.Groups[1].Value
    Write-Host "Last run: $lastRun"
  }
  Write-Host ""
  if (Test-Path $STATE_DIR) {
    Get-ChildItem $STATE_DIR | Where-Object { $_.Name -ne "meta" } | ForEach-Object {
      Write-Host "  $($_.Name) = $(Get-Content $_.FullName)"
    }
  }
  exit 0
}

# ── Read schema ──
$CURRENT_SCHEMA = (Select-String -Path $WORKFLOWS_JSON -Pattern 'schema":s*(d+)' | ForEach-Object { $_.Matches.Groups[1].Value } | Select-Object -First 1)
$STORED_SCHEMA = if (Test-Path $STATE_META) { (Get-Content $STATE_META | Select-String "SCHEMA=(.*)" | ForEach-Object { $_.Matches.Groups[1].Value }) } else { $null }

# ── Drift detection ──
if ($STORED_SCHEMA -and $STORED_SCHEMA -ne $CURRENT_SCHEMA) {
  Write-Host "Setup scripts updated to version $CURRENT_SCHEMA (was $STORED_SCHEMA)."
}

# ── Update state meta ──
"SCHEMA=$CURRENT_SCHEMA" | Out-File $STATE_META -Encoding UTF8
"LAST_RUN=$(Get-Date -Format yyyy-MM-dd)" | Out-File $STATE_META -Append -Encoding UTF8

# ── Run target script ──
$TARGET_SCRIPT = Join-Path $PROJECT_IGNITER_DIR "scripts" $PROJECT_KEY $ENV "setup.ps1"
if (-not (Test-Path $TARGET_SCRIPT)) {
  Write-Error "No setup script found for project=$PROJECT_KEY env=$ENV"
  Write-Error "  Expected: $TARGET_SCRIPT"
  exit 1
}

& $TARGET_SCRIPT
